name: Chromatic
on: push

jobs:
  chromatic:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pnpm install

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: chpt_37bf1cc1532495a
          # ${{ secrets.CHROMATIC_PROJECT_TOKEN
          exitZeroOnChanges: true
          workingDir: "apps/frontend/package.json"
